exclude: '^$'
fail_fast: false
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        args: [--allow-multiple-documents]
        stages: [pre-commit]
      - id: check-xml
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
      - id: destroyed-symlinks
        stages: [pre-commit]
      - id: mixed-line-ending
        exclude: "(^.idea/|.vscode/)"
        stages: [pre-commit]
      - id: trailing-whitespace
        exclude: "(^.idea/|.vscode/)"
        stages: [pre-commit]
      - id: end-of-file-fixer
        exclude: "(^.idea/|.vscode/)"
        stages: [pre-commit]
